#  En la carpeta raiz ejecuto : docker build -t proyectobbddback .
#  En la carpeta dockercomposeconfig: docker compose up -d
version: '3.8'

services:
  mysql:
    container_name: "MySQLBasedeDatos"
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: proyecto
      MYSQL_DATABASE: proyectoback
    volumes:
      - ./dockercomposeconfig/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongodb_data:
